import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Pencil } from "lucide-react";
import { useOutletContext } from "react-router";
import type { AuthOutletContext } from "./_user";

export default function () {
  const { gadgetConfig, user } = useOutletContext<AuthOutletContext>();

  return (
    <div className="container mx-auto p-6">
      <div className="grid gap-6">
        <div>
          <Card className="overflow-hidden">
            <div className="flex items-start justify-between p-8 bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800">
              <div className="space-y-6">
                <h2 className="text-3xl font-bold text-primary">Welcome to NeuroFlows – Where Learning Adapts to You!</h2>
                <div className="space-y-4">
                  <p className="text-lg">
                    We're thrilled to have you on board at <span className="font-semibold text-primary">{gadgetConfig.env.GADGET_APP}</span>!
                  </p>
                  <p className="text-base">
                    NeuroFlows is designed to adapt to your unique learning style, helping you master new skills at your own pace.
                  </p>
                  <p className="text-base">
                    Explore personalized learning paths, interactive content, and track your progress in real-time.
                  </p>
                </div>
                <div className="flex gap-3 mt-2">
                  <Button
                    className="bg-primary hover:bg-primary/90"
                    onClick={() => {
                      alert("Start your learning journey");
                    }}
                  >
                    Start Learning
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => {
                      window.open(
                        "/edit/files/web/routes/_user.signed-in.tsx",
                        "_blank"
                      );
                    }}
                  >
                    <Pencil className="mr-2 h-4 w-4" />
                    Edit this page
                  </Button>
                </div>
              </div>
              <div className="bg-white dark:bg-slate-700 rounded-full p-3 shadow-md">
                <img
                  src="https://assets.gadget.dev/assets/default-app-assets/react-logo.svg"
                  className="app-logo h-24 w-24 animate-pulse"
                  alt="NeuroFlows logo"
                />
              </div>
            </div>
          </Card>
        </div>
        <Card className="p-6">
          <div className="space-y-6">
            <h2 className="text-xl font-semibold">Current user</h2>
            <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div>
                <dt className="text-sm font-medium text-muted-foreground">
                  ID
                </dt>
                <dd className="text-base">{user.id}</dd>
              </div>
              <div>
                <dt className="text-sm font-medium text-muted-foreground">
                  Name
                </dt>
                <dd className="text-base">{`${user.firstName} ${user.lastName}`}</dd>
              </div>
              <div>
                <dt className="text-sm font-medium text-muted-foreground">
                  Email
                </dt>
                <dd className="text-base">
                  <a
                    href={`mailto:${user.email}`}
                    className="text-primary hover:underline"
                  >
                    {user.email}
                  </a>
                </dd>
              </div>
              <div>
                <dt className="text-sm font-medium text-muted-foreground">
                  Created
                </dt>
                <dd className="text-base">
                  {user.createdAt.toLocaleString("en-US", { timeZone: "UTC" })} (in UTC)
                </dd>
              </div>
            </dl>
            <div className="space-y-4">
              <p className="text-sm text-muted-foreground">
                This data is fetched from your{" "}
                <a
                  href="/edit/development/models/user"
                  className="text-primary hover:underline"
                >
                  user
                </a>{" "}
                via your autogenerated API.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
